// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJw7AaQgrtsr7ypJIOdPb5bY132JRE2N0',
    appId: '1:892272057115:web:6e3954f5e22dc7c59dd1be',
    messagingSenderId: '892272057115',
    projectId: 'aida-chatbot-1bcb4',
    authDomain: 'aida-chatbot-1bcb4.firebaseapp.com',
    storageBucket: 'aida-chatbot-1bcb4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwc7yCVhf9i1SP6NPOalb2ne6IEIpTrlM',
    appId: '1:892272057115:android:cba78aba9112941d9dd1be',
    messagingSenderId: '892272057115',
    projectId: 'aida-chatbot-1bcb4',
    storageBucket: 'aida-chatbot-1bcb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3dZ6kdaCDumCy2It1-R6QZCt4_LVrZI',
    appId: '1:892272057115:ios:86af1ba73039f3199dd1be',
    messagingSenderId: '892272057115',
    projectId: 'aida-chatbot-1bcb4',
    storageBucket: 'aida-chatbot-1bcb4.firebasestorage.app',
    iosBundleId: 'com.example.aida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3dZ6kdaCDumCy2It1-R6QZCt4_LVrZI',
    appId: '1:892272057115:ios:86af1ba73039f3199dd1be',
    messagingSenderId: '892272057115',
    projectId: 'aida-chatbot-1bcb4',
    storageBucket: 'aida-chatbot-1bcb4.firebasestorage.app',
    iosBundleId: 'com.example.aida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJw7AaQgrtsr7ypJIOdPb5bY132JRE2N0',
    appId: '1:892272057115:web:33f66f1df9e51c699dd1be',
    messagingSenderId: '892272057115',
    projectId: 'aida-chatbot-1bcb4',
    authDomain: 'aida-chatbot-1bcb4.firebaseapp.com',
    storageBucket: 'aida-chatbot-1bcb4.firebasestorage.app',
  );
}
